### ISSUE TITLE
CLI Next

### ISSUE THREAD

**Issue by heyMP** [elmsln/wcfactory#59]
## Why?
The CLI is how users are going to interface with wcfactory.  We want it to be as smooth as possible.  Yeoman is a great tool but it's not specifically made to be a CLI.  In their documentation they talk about [how you can use yeoman generators behind the scenes in your CLI](http://yeoman.io/authoring/integrating-yeoman.html).

## What?
There are some CLI specific frameworks that I've been taking a look at:

- OCLIF https://github.com/oclif/oclif
- Ace CLI https://adonisjs.com/docs/4.1/ace
- Commander.js https://github.com/tj/commander.js/
- Vorpal.js https://vorpal.js.org/

## How?
I took an initial stab at moving from commander.js to OCLIF.   My thinking is that we do the following.
- move all prompts from yeoman generators to the cli
- ~~move all install script stuff to cli~~ we can keep these in the generator for now.
- pass arguments from cli to yeoman generator via yeoman-environment
- wrap processes in a nice [Listr](https://github.com/SamVerschueren/listr) type of output so it doesn't get overwhelming for the users.
- use yoeman-generators for copyTpl processes only (unless there is something else that it does better)
- 💰 profit

## Todos
- ~~create custom listr renderer for showing install steps nicely~~
- [x] migrate init generator
- [x] migrate app generator
- [x] migrate wrapper generator
- [x] change command to be `wcf` instead of `wcfactory`
- [x] update documentation
- [x] migrate product generator
- [x] have CLI recognize commands :)

**Comment by btopro** [comment]
@heyMP I added a task, while your in the CLI can you change the call to `wcf` so we save on characters that much more
